---
- name: Debian development machine setup
  hosts: machines
  become: true

  vars_files:
    - vars/main.yaml

  pre_tasks:
  - name: Update apt cache if needed
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600

  tasks:
    - ansible.builtin.import_tasks: tasks/packages-install.yaml
    - ansible.builtin.import_tasks: tasks/zsh_omz.yaml
    - ansible.builtin.import_tasks: tasks/docker.yaml


  roles:
    - role: geerlingguy.dotfiles
      when: configure_dotfiles