---
- name: Ubuntu development machine setup
  hosts: ubuntu_dev
  become: true

  vars_files:
    - vars/main.yml

  pre_tasks:
  - name: Update apt cache if needed
    apt:
      update_cache: yes
      cache_valid_time: 3600

  tasks:
    - import_tasks: tasks/common.yml
    - import_tasks: tasks/install_apt.yml
    - import_tasks: tasks/docker.yml


  roles:
    - role: geerlingguy.dotfiles
      when: configure_dotfiles